apiVersion: skaffold/v2alpha3
kind: Config
build:
    # local:
    #   push: false
    googleCloudBuild:
        projectId: ticketing-sh
    artifacts:
        - image: us.gcr.io/ticketing-sh/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: us.gcr.io/ticketing-sh/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.js'
                    dest: .
        - image: us.gcr.io/ticketing-sh/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: us.gcr.io/ticketing-sh/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: us.gcr.io/ticketing-sh/expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: us.gcr.io/ticketing-sh/payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
deploy:
    kubectl:
        manifests:
            - ./infrastructure/k8s/*
