apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                #   image: us.gcr.io/ticketing-sh/auth
                  image: jopealgorta/ticketing-auth
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://auth-mongo-cluster-ip-service:27017/auth'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-key
                                key: JWT_KEY
