apiVersion: apps/v1
kind: Deployment
metadata:
    name: orders-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: orders
    template:
        metadata:
            labels:
                app: orders
        spec:
            containers:
                - name: orders
                  image: us.gcr.io/ticketing-sh/orders
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://orders-mongo-cluster-ip-service:27017/orders'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-key
                                key: JWT_KEY
                      - name: NATS_URL
                        value: 'http://nats-cluster-ip-service:4222'
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
