apiVersion: apps/v1
kind: Deployment
metadata:
    name: payments-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payments
    template:
        metadata:
            labels:
                app: payments
        spec:
            containers:
                - name: payments
                  # image: us.gcr.io/ticketing-sh/payments
                  image: jopealgorta/ticketing-payments
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://payments-mongo-cluster-ip-service:27017/payments'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-key
                                key: JWT_KEY
                      - name: STRIPE_KEY
                        valueFrom:
                            secretKeyRef:
                                name: stripe-secret
                                key: STRIPE_KEY
                      - name: NATS_URL
                        value: 'http://nats-cluster-ip-service:4222'
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
